### ISSUE TITLE
HistoricTransactions.py access 'from' in transaction

### ISSUE THREAD

**Issue by japan2k20** [whaletrace/api#1]
Hi,
I am new to the whaletrace API (and in python in general).
I have run the historicTransaction.py script, it works fine.

I am trying to access each transaction.to and each transaction.from information
It works fine for the first one (transaction.to) but it does not work for transaction.from because from is a reserved keyword in python I guess. In this case, how do you access the 'from' information ?

**Comment by whaletrace** [comment]
Please see the [example of client](https://github.com/whaletrace/api/blob/master/python/HistoricTransactions/client.py) for Historic transactions. The retrieval of `from` and `to` attribute is mentioned there: 
```
in our case we have to use kwarg because `from` is
is recognized as python keyword so there would syntax be error
if you want get value you have to use getattr()
```

**Comment by japan2k20** [comment]
It works ! thank you !
